In [11]:
'''
@author: brianwsyang
@date: Thu Jun 17 2021
'''

'\n@author: brianwsyang\n@date: Thu Jun 17 2021\n'

In [12]:
import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt

In [13]:
df = pd.read_csv('heart_attack_data.csv')
df.drop(columns=['exng', 'oldpeak', 'slp', 'caa', 'thall'],
        inplace=True)

In [14]:
df.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  output
0   63    1   3     145   233    1        0       150       1
1   37    1   2     130   250    0        1       187       1
2   41    0   1     130   204    0        0       172       1
3   56    1   1     120   236    0        1       178       1
4   57    0   0     120   354    0        1       163       1

In [15]:
# df.info()

In [16]:
# df.describe()

In [19]:
# df divided by sex
male_df = df[df.sex == 1]
female_df = df[df.sex == 0]

# df divided by output
ha1_df = df[df.output == 1]
ha0_df = df[df.output == 0]

In [ ]:
N = 5
g1 = (0.6 + 0.6 * np.random.rand(N), np.random.rand(N))
g2 = (0.4+0.3 * np.random.rand(N), 0.5*np.random.rand(N))
g3 = (0.3*np.random.rand(N),0.3*np.random.rand(N))

data = (g1, g2, g3)
colors = ('red', 'green', 'blue')
groups = ('coffee', 'tea', 'water')

for d in data:
    print(d)
print('-')
for z in zip(data, colors, groups):
    print(z)

for data, color, group in zip(data, colors, groups):
    x, y = data
    # print(data, color, group)


(array([0.84622093, 0.89507217, 0.67121155, 0.94087459, 0.78091819]), array([0.93172643, 0.7415425 , 0.33072675, 0.78743065, 0.69475502]))
(array([0.43111466, 0.40501208, 0.67149065, 0.67991977, 0.59040321]), array([0.48343156, 0.25629696, 0.00807546, 0.26657754, 0.02822392]))
(array([0.18457519, 0.24428447, 0.17417409, 0.29948779, 0.15028674]), array([0.10352368, 0.12145202, 0.1755036 , 0.11708448, 0.04152478]))
-
((array([0.84622093, 0.89507217, 0.67121155, 0.94087459, 0.78091819]), array([0.93172643, 0.7415425 , 0.33072675, 0.78743065, 0.69475502])), 'red', 'coffee')
((array([0.43111466, 0.40501208, 0.67149065, 0.67991977, 0.59040321]), array([0.48343156, 0.25629696, 0.00807546, 0.26657754, 0.02822392])), 'green', 'tea')
((array([0.18457519, 0.24428447, 0.17417409, 0.29948779, 0.15028674]), array([0.10352368, 0.12145202, 0.1755036 , 0.11708448, 0.04152478])), 'blue', 'water')
